name: Deploy Backend to Server

on:
  push:
    branches:
      - dev1
      - dev2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Print branch name
        run: |
          echo "Current branch: ${{ github.ref_name }}"

      - name: Set environment variables based on branch
        run: |
          echo "DEPLOY_HOST=${{ secrets.REMOTE_HOST_DEV1 }}" >> $GITHUB_ENV
          echo "DEPLOY_USER=${{ secrets.REMOTE_USER_DEV1 }}" >> $GITHUB_ENV

      - name: Set environment variables based on branch
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/production" ]]; then
            echo "DEPLOY_HOST=${{ secrets.REMOTE_HOST_PROD }}" >> $GITHUB_ENV
            echo "DEPLOY_USER=${{ secrets.REMOTE_USER_PROD }}" >> $GITHUB_ENV
            echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY_PROD }}" >> $GITHUB_ENV
          else
            echo "DEPLOY_HOST=${{ secrets.REMOTE_HOST_DEV1 }}" >> $GITHUB_ENV
            echo "DEPLOY_USER=${{ secrets.REMOTE_USER_DEV1 }}" >> $GITHUB_ENV
            echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
          fi

      - name: Set up SSH and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/${{ github.ref_name }}/
            ./scripts/update-backend.sh
